name: Flutter CI/CD
on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request'
    steps:
      - name: set up repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: kuhnroyal/flutter-fvm-config-action@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true
      - run: flutter analyze > flutter_analyze_report.txt
        continue-on-error: true
      - run: perl -pi -e 's/^warning/info/' flutter_analyze_report.txt
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: MeilCli/danger-action@v5
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
